window.LAST_UPDATED = "1/19/2026, 11:19:28 PM";
window.LATEST_PICKS = [
  {
    "player": "Russell Westbrook",
    "team": "SAC",
    "pos": "PG",
    "opp": "MIA",
    "stat": "ra",
    "side": "OVER",
    "line": 11.5,
    "projection": "18.08",
    "edge": "6.58",
    "ease": 0.76,
    "marketLine": "11.5",
    "betRating": "🔒 PROPHET LOCK",
    "confidence": 0.99,
    "confidenceGrade": "A+ 🌟",
    "score": "17.91",
    "interpretation": "Matchup: Positive Ease → Environment supports stat accumulation. | Pos: <span style=\"color:#4ade80\">0.76</span> | Team: <span style=\"color:#4ade80\">0.75</span>",
    "analysis": "💰 **Value Play**: We are capturing **6.58 points of implied value** here.<br>✅ **Smash Spot**: MIA defense is bleeding Reb+Ast to this position (Ease: +0.76). High ceiling environment.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Aaron Gordon",
    "team": "DEN",
    "pos": "PF",
    "opp": "LAL",
    "stat": "p",
    "side": "OVER",
    "line": 18.5,
    "projection": "24.73",
    "edge": "6.23",
    "ease": -0.611,
    "marketLine": "18.5",
    "betRating": "🔒 PROPHET LOCK",
    "confidence": 0.99,
    "confidenceGrade": "A+ 🌟",
    "score": "15.42",
    "interpretation": "Matchup: Negative Ease → Contradicts Over (check usage). | Pos: <span style=\"color:#f87171\">-0.61</span> | Team: <span style=\"color:#4ade80\">0.40</span>",
    "analysis": "💰 **Value Play**: We are capturing **6.23 points of implied value** here.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Brice Sensabaugh",
    "team": "UTA",
    "pos": "SF",
    "opp": "MIN",
    "stat": "pr",
    "side": "UNDER",
    "line": 22,
    "projection": "15.91",
    "edge": "6.09",
    "ease": -0.5189999999999999,
    "marketLine": "22",
    "betRating": "🔒 PROPHET LOCK",
    "confidence": 0.99,
    "confidenceGrade": "A+ 🌟",
    "score": "13.57",
    "interpretation": "Matchup: Negative Ease → Environment suppresses stat (Confirms Under). | Pos: <span style=\"color:#f87171\">-0.52</span> | Team: <span style=\"color:#f87171\">-0.45</span>",
    "analysis": "💰 **Value Play**: We are capturing **6.09 points of implied value** here.<br>🔒 **Defensive Clamp**: MIN ranks elite vs Pts+Reb. Expect usage to struggle.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T02:10:00Z"
  },
  {
    "player": "Aaron Gordon",
    "team": "DEN",
    "pos": "PF",
    "opp": "LAL",
    "stat": "pa",
    "side": "OVER",
    "line": 21.5,
    "projection": "27.58",
    "edge": "6.08",
    "ease": 0.009000000000000008,
    "marketLine": "21.5",
    "betRating": "🔒 PROPHET LOCK",
    "confidence": 0.99,
    "confidenceGrade": "A+ 🌟",
    "score": "13.54",
    "interpretation": "Matchup: Neutral Ease → Edge drives the bet. | Pos: <span style=\"color:#4ade80\">0.01</span> | Team: <span style=\"color:#4ade80\">0.05</span>",
    "analysis": "💰 **Value Play**: We are capturing **6.08 points of implied value** here.<br>⚖️ **Neutral Spot**: Matchup is average, but the volume projection (27.6) carries the play.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Brice Sensabaugh",
    "team": "UTA",
    "pos": "SF",
    "opp": "MIN",
    "stat": "pra",
    "side": "UNDER",
    "line": 24.5,
    "projection": "18.11",
    "edge": "6.39",
    "ease": -0.49766666666666665,
    "marketLine": "24.5",
    "betRating": "🔒 PROPHET LOCK",
    "confidence": 0.99,
    "confidenceGrade": "A+ 🌟",
    "score": "13.44",
    "interpretation": "Matchup: Negative Ease → Environment suppresses stat (Confirms Under). | Pos: <span style=\"color:#f87171\">-0.50</span> | Team: <span style=\"color:#f87171\">-0.35</span>",
    "analysis": "💰 **Value Play**: We are capturing **6.39 points of implied value** here.<br>🔒 **Defensive Clamp**: MIN ranks elite vs Pts+Reb+Ast. Expect usage to struggle.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T02:10:00Z"
  },
  {
    "player": "Aaron Gordon",
    "team": "DEN",
    "pos": "PF",
    "opp": "LAL",
    "stat": "pr",
    "side": "OVER",
    "line": 25.5,
    "projection": "31.53",
    "edge": "6.03",
    "ease": -0.832,
    "marketLine": "25.5",
    "betRating": "🔒 PROPHET LOCK",
    "confidence": 0.99,
    "confidenceGrade": "A+ 🌟",
    "score": "13.43",
    "interpretation": "Matchup: Negative Ease → Contradicts Over (check usage). | Pos: <span style=\"color:#f87171\">-0.83</span> | Team: <span style=\"color:#f87171\">-0.58</span>",
    "analysis": "💰 **Value Play**: We are capturing **6.03 points of implied value** here.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Brice Sensabaugh",
    "team": "UTA",
    "pos": "SF",
    "opp": "MIN",
    "stat": "p",
    "side": "UNDER",
    "line": 17.5,
    "projection": "12.41",
    "edge": "5.09",
    "ease": 0.15499999999999994,
    "marketLine": "17.5",
    "betRating": "🔒 PROPHET LOCK",
    "confidence": 0.99,
    "confidenceGrade": "A+ 🌟",
    "score": "12.60",
    "interpretation": "Matchup: Positive Ease → Contradicts Under. | Pos: <span style=\"color:#4ade80\">0.15</span> | Team: <span style=\"color:#4ade80\">0.14</span>",
    "analysis": "💰 **Value Play**: We are capturing **5.09 points of implied value** here.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T02:10:00Z"
  },
  {
    "player": "Aaron Gordon",
    "team": "DEN",
    "pos": "PF",
    "opp": "LAL",
    "stat": "pra",
    "side": "OVER",
    "line": 28.5,
    "projection": "34.38",
    "edge": "5.88",
    "ease": -0.345,
    "marketLine": "28.5",
    "betRating": "🔒 PROPHET LOCK",
    "confidence": 0.99,
    "confidenceGrade": "A+ 🌟",
    "score": "12.37",
    "interpretation": "Matchup: Negative Ease → Contradicts Over (check usage). | Pos: <span style=\"color:#f87171\">-0.34</span> | Team: <span style=\"color:#f87171\">-0.48</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **5.88 point gap** vs public perception.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Russell Westbrook",
    "team": "SAC",
    "pos": "PG",
    "opp": "MIA",
    "stat": "a",
    "side": "OVER",
    "line": 6.5,
    "projection": "9.54",
    "edge": "3.04",
    "ease": 0.201,
    "marketLine": "6.5",
    "betRating": "🔒 PROPHET LOCK",
    "confidence": 0.99,
    "confidenceGrade": "A+ 🌟",
    "score": "12.04",
    "interpretation": "Matchup: Positive Ease → Environment supports stat accumulation. | Pos: <span style=\"color:#4ade80\">0.20</span> | Team: <span style=\"color:#4ade80\">0.04</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.04 point gap** vs public perception.<br>✅ **Smash Spot**: MIA defense is bleeding Assists to this position (Ease: +0.201). High ceiling environment.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Peyton Watson",
    "team": "DEN",
    "pos": "SF",
    "opp": "LAL",
    "stat": "pr",
    "side": "UNDER",
    "line": 25.5,
    "projection": "20.35",
    "edge": "5.15",
    "ease": 0.20850000000000002,
    "marketLine": "25.5",
    "betRating": "🔒 PROPHET LOCK",
    "confidence": 0.99,
    "confidenceGrade": "A+ 🌟",
    "score": "11.47",
    "interpretation": "Matchup: Positive Ease → Contradicts Under. | Pos: <span style=\"color:#4ade80\">0.21</span> | Team: <span style=\"color:#f87171\">-0.58</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **5.15 point gap** vs public perception.<br>✅ **Smash Spot**: LAL defense is bleeding Pts+Reb to this position (Ease: +0.20850000000000002). High ceiling environment.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Peyton Watson",
    "team": "DEN",
    "pos": "SF",
    "opp": "LAL",
    "stat": "p",
    "side": "UNDER",
    "line": 19.5,
    "projection": "14.92",
    "edge": "4.58",
    "ease": 1.241,
    "marketLine": "19.5",
    "betRating": "🔒 PROPHET LOCK",
    "confidence": 0.99,
    "confidenceGrade": "A+ 🌟",
    "score": "11.34",
    "interpretation": "Matchup: Positive Ease → Contradicts Under. | Pos: <span style=\"color:#4ade80\">1.24</span> | Team: <span style=\"color:#4ade80\">0.40</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **4.58 point gap** vs public perception.<br>✅ **Smash Spot**: LAL defense is bleeding Points to this position (Ease: +1.241). High ceiling environment.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Russell Westbrook",
    "team": "SAC",
    "pos": "PG",
    "opp": "MIA",
    "stat": "r",
    "side": "OVER",
    "line": 5.5,
    "projection": "8.54",
    "edge": "3.04",
    "ease": 1.319,
    "marketLine": "5.5",
    "betRating": "🔒 PROPHET LOCK",
    "confidence": 0.99,
    "confidenceGrade": "A+ 🌟",
    "score": "11.29",
    "interpretation": "Matchup: Positive Ease → Environment supports stat accumulation. | Pos: <span style=\"color:#4ade80\">1.32</span> | Team: <span style=\"color:#4ade80\">1.45</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.04 point gap** vs public perception.<br>✅ **Smash Spot**: MIA defense is bleeding Rebounds to this position (Ease: +1.319). High ceiling environment.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Lauri Markkanen",
    "team": "UTA",
    "pos": "SF",
    "opp": "MIN",
    "stat": "pr",
    "side": "UNDER",
    "line": 34.5,
    "projection": "29.65",
    "edge": "4.85",
    "ease": -0.5189999999999999,
    "marketLine": "34.5",
    "betRating": "🔒 PROPHET LOCK",
    "confidence": 0.99,
    "confidenceGrade": "A+ 🌟",
    "score": "10.80",
    "interpretation": "Matchup: Negative Ease → Environment suppresses stat (Confirms Under). | Pos: <span style=\"color:#f87171\">-0.52</span> | Team: <span style=\"color:#f87171\">-0.45</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **4.85 point gap** vs public perception.<br>🔒 **Defensive Clamp**: MIN ranks elite vs Pts+Reb. Expect usage to struggle.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T02:10:00Z"
  },
  {
    "player": "Lauri Markkanen",
    "team": "UTA",
    "pos": "SF",
    "opp": "MIN",
    "stat": "pra",
    "side": "UNDER",
    "line": 36.5,
    "projection": "31.53",
    "edge": "4.97",
    "ease": -0.49766666666666665,
    "marketLine": "36.5",
    "betRating": "💎 DIAMOND BOY",
    "confidence": 0.99,
    "confidenceGrade": "A+ 🌟",
    "score": "10.46",
    "interpretation": "Matchup: Negative Ease → Environment suppresses stat (Confirms Under). | Pos: <span style=\"color:#f87171\">-0.50</span> | Team: <span style=\"color:#f87171\">-0.35</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **4.97 point gap** vs public perception.<br>🔒 **Defensive Clamp**: MIN ranks elite vs Pts+Reb+Ast. Expect usage to struggle.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T02:10:00Z"
  },
  {
    "player": "Peyton Watson",
    "team": "DEN",
    "pos": "SF",
    "opp": "LAL",
    "stat": "pra",
    "side": "UNDER",
    "line": 27.5,
    "projection": "22.70",
    "edge": "4.80",
    "ease": 0.26566666666666666,
    "marketLine": "27.5",
    "betRating": "💎 DIAMOND BOY",
    "confidence": 0.99,
    "confidenceGrade": "A+ 🌟",
    "score": "10.10",
    "interpretation": "Matchup: Positive Ease → Contradicts Under. | Pos: <span style=\"color:#4ade80\">0.27</span> | Team: <span style=\"color:#f87171\">-0.48</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **4.80 point gap** vs public perception.<br>✅ **Smash Spot**: LAL defense is bleeding Pts+Reb+Ast to this position (Ease: +0.26566666666666666). High ceiling environment.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Russell Westbrook",
    "team": "SAC",
    "pos": "PG",
    "opp": "MIA",
    "stat": "pra",
    "side": "OVER",
    "line": 27.5,
    "projection": "32.26",
    "edge": "4.76",
    "ease": 0.6643333333333333,
    "marketLine": "27.5",
    "betRating": "💎 DIAMOND BOY",
    "confidence": 0.99,
    "confidenceGrade": "A+ 🌟",
    "score": "10.01",
    "interpretation": "Matchup: Positive Ease → Environment supports stat accumulation. | Pos: <span style=\"color:#4ade80\">0.66</span> | Team: <span style=\"color:#4ade80\">0.66</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **4.76 point gap** vs public perception.<br>✅ **Smash Spot**: MIA defense is bleeding Pts+Reb+Ast to this position (Ease: +0.6643333333333333). High ceiling environment.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Jamal Murray",
    "team": "DEN",
    "pos": "PG",
    "opp": "LAL",
    "stat": "a",
    "side": "OVER",
    "line": 8.5,
    "projection": "11.02",
    "edge": "2.52",
    "ease": -0.22000000000000003,
    "marketLine": "8.5",
    "betRating": "💎 DIAMOND BOY",
    "confidence": 0.99,
    "confidenceGrade": "A+ 🌟",
    "score": "9.98",
    "interpretation": "Matchup: Negative Ease → Contradicts Over (check usage). | Pos: <span style=\"color:#f87171\">-0.22</span> | Team: <span style=\"color:#f87171\">-0.29</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.52 point gap** vs public perception.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "VJ Edgecombe",
    "team": "PHI",
    "pos": "PG",
    "opp": "PHO",
    "stat": "pr",
    "side": "OVER",
    "line": 19.5,
    "projection": "24.08",
    "edge": "4.58",
    "ease": -0.21400000000000008,
    "marketLine": "19.5",
    "betRating": "💎 DIAMOND BOY",
    "confidence": 0.934941176470588,
    "confidenceGrade": "A",
    "score": "9.63",
    "interpretation": "Matchup: Negative Ease → Contradicts Over (check usage). | Pos: <span style=\"color:#f87171\">-0.21</span> | Team: <span style=\"color:#4ade80\">0.11</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **4.58 point gap** vs public perception.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T00:10:00Z"
  },
  {
    "player": "VJ Edgecombe",
    "team": "PHI",
    "pos": "PG",
    "opp": "PHO",
    "stat": "p",
    "side": "OVER",
    "line": 14.5,
    "projection": "18.52",
    "edge": "4.02",
    "ease": 0.33299999999999996,
    "marketLine": "14.5",
    "betRating": "💎 DIAMOND BOY",
    "confidence": 0.9229411764705882,
    "confidenceGrade": "A",
    "score": "9.28",
    "interpretation": "Matchup: Positive Ease → Environment supports stat accumulation. | Pos: <span style=\"color:#4ade80\">0.33</span> | Team: <span style=\"color:#f87171\">-0.20</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **4.02 point gap** vs public perception.<br>✅ **Smash Spot**: PHO defense is bleeding Points to this position (Ease: +0.33299999999999996). High ceiling environment.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T00:10:00Z"
  },
  {
    "player": "Lauri Markkanen",
    "team": "UTA",
    "pos": "SF",
    "opp": "MIN",
    "stat": "p",
    "side": "UNDER",
    "line": 26.5,
    "projection": "22.66",
    "edge": "3.84",
    "ease": 0.15499999999999994,
    "marketLine": "26.5",
    "betRating": "💎 DIAMOND BOY",
    "confidence": 0.9517647058823525,
    "confidenceGrade": "A+ 🌟",
    "score": "9.14",
    "interpretation": "Matchup: Positive Ease → Contradicts Under. | Pos: <span style=\"color:#4ade80\">0.15</span> | Team: <span style=\"color:#4ade80\">0.14</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.84 point gap** vs public perception.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T02:10:00Z"
  },
  {
    "player": "Adem Bona",
    "team": "PHI",
    "pos": "C",
    "opp": "PHO",
    "stat": "r",
    "side": "OVER",
    "line": 4.5,
    "projection": "7.13",
    "edge": "2.63",
    "ease": 1.1320000000000001,
    "marketLine": "4.5",
    "betRating": "💎 DIAMOND BOY",
    "confidence": 0.9141176470588235,
    "confidenceGrade": "A",
    "score": "9.02",
    "interpretation": "Matchup: Positive Ease → Environment supports stat accumulation. | Pos: <span style=\"color:#4ade80\">1.13</span> | Team: <span style=\"color:#4ade80\">0.42</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.63 point gap** vs public perception.<br>✅ **Smash Spot**: PHO defense is bleeding Rebounds to this position (Ease: +1.1320000000000001). High ceiling environment.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T00:10:00Z"
  },
  {
    "player": "Rudy Gobert",
    "team": "MIN",
    "pos": "C",
    "opp": "UTA",
    "stat": "r",
    "side": "UNDER",
    "line": 13.5,
    "projection": "11.08",
    "edge": "2.42",
    "ease": 0.116,
    "marketLine": "13.5",
    "betRating": "🔥 ELITE",
    "confidence": 0.9570588235294117,
    "confidenceGrade": "A+ 🌟",
    "score": "8.69",
    "interpretation": "Matchup: Positive Ease → Contradicts Under. | Pos: <span style=\"color:#4ade80\">0.12</span> | Team: <span style=\"color:#4ade80\">0.06</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.42 point gap** vs public perception.",
    "startTime": "2026-01-21T02:10:00Z"
  },
  {
    "player": "Ochai Agbaji",
    "team": "TOR",
    "pos": "SG",
    "opp": "GSW",
    "stat": "pr",
    "side": "OVER",
    "line": 8.5,
    "projection": "12.44",
    "edge": "3.94",
    "ease": -0.49799999999999994,
    "marketLine": "8.5",
    "betRating": "🔥 ELITE",
    "confidence": 0.9471764705882353,
    "confidenceGrade": "A+ 🌟",
    "score": "8.40",
    "interpretation": "Matchup: Negative Ease → Contradicts Over (check usage). | Pos: <span style=\"color:#f87171\">-0.50</span> | Team: <span style=\"color:#f87171\">-0.19</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.94 point gap** vs public perception.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Immanuel Quickley",
    "team": "TOR",
    "pos": "PG",
    "opp": "GSW",
    "stat": "pr",
    "side": "OVER",
    "line": 19.5,
    "projection": "23.41",
    "edge": "3.91",
    "ease": -0.0030000000000000027,
    "marketLine": "19.5",
    "betRating": "🔥 ELITE",
    "confidence": 0.9440000000000001,
    "confidenceGrade": "A+ 🌟",
    "score": "8.30",
    "interpretation": "Matchup: Neutral Ease → Edge drives the bet. | Pos: <span style=\"color:#f87171\">-0.00</span> | Team: <span style=\"color:#f87171\">-0.19</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.91 point gap** vs public perception.<br>⚖️ **Neutral Spot**: Matchup is average, but the volume projection (23.4) carries the play.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Stephen Curry",
    "team": "GSW",
    "pos": "PG",
    "opp": "TOR",
    "stat": "a",
    "side": "UNDER",
    "line": 6.5,
    "projection": "4.08",
    "edge": "2.42",
    "ease": -0.5860000000000001,
    "marketLine": "6.5",
    "betRating": "🔥 ELITE",
    "confidence": 0.8555294117647059,
    "confidenceGrade": "A-",
    "score": "8.28",
    "interpretation": "Matchup: Negative Ease → Environment suppresses stat (Confirms Under). | Pos: <span style=\"color:#f87171\">-0.59</span> | Team: <span style=\"color:#f87171\">-1.04</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.42 point gap** vs public perception.<br>🔒 **Defensive Clamp**: TOR ranks elite vs Assists. Expect usage to struggle.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Scottie Barnes",
    "team": "TOR",
    "pos": "SG",
    "opp": "GSW",
    "stat": "pa",
    "side": "UNDER",
    "line": 26.5,
    "projection": "22.78",
    "edge": "3.72",
    "ease": 0.143,
    "marketLine": "26.5",
    "betRating": "💪 STRONG PLAY",
    "confidence": 0.9238823529411764,
    "confidenceGrade": "A",
    "score": "7.73",
    "interpretation": "Matchup: Positive Ease → Contradicts Under. | Pos: <span style=\"color:#4ade80\">0.14</span> | Team: <span style=\"color:#f87171\">-0.28</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.72 point gap** vs public perception.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Anthony Edwards",
    "team": "MIN",
    "pos": "PG",
    "opp": "UTA",
    "stat": "pra",
    "side": "UNDER",
    "line": 40,
    "projection": "36.17",
    "edge": "3.83",
    "ease": -0.056333333333333326,
    "marketLine": "40",
    "betRating": "💪 STRONG PLAY",
    "confidence": 0.9129999999999998,
    "confidenceGrade": "A",
    "score": "7.43",
    "interpretation": "Matchup: Neutral Ease → Edge drives the bet. | Pos: <span style=\"color:#f87171\">-0.06</span> | Team: <span style=\"color:#4ade80\">1.01</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.83 point gap** vs public perception.<br>⚖️ **Neutral Spot**: Matchup is average, but the volume projection (36.2) carries the play.",
    "startTime": "2026-01-21T02:10:00Z"
  },
  {
    "player": "Ochai Agbaji",
    "team": "TOR",
    "pos": "SG",
    "opp": "GSW",
    "stat": "p",
    "side": "OVER",
    "line": 5.5,
    "projection": "8.68",
    "edge": "3.18",
    "ease": -0.10800000000000003,
    "marketLine": "5.5",
    "betRating": "💪 STRONG PLAY",
    "confidence": 0.9041176470588235,
    "confidenceGrade": "A",
    "score": "7.19",
    "interpretation": "Matchup: Negative Ease → Contradicts Over (check usage). | Pos: <span style=\"color:#f87171\">-0.11</span> | Team: <span style=\"color:#f87171\">-0.72</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.18 point gap** vs public perception.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "James Harden",
    "team": "LAC",
    "pos": "PG",
    "opp": "CHI",
    "stat": "a",
    "side": "UNDER",
    "line": 9.5,
    "projection": "7.30",
    "edge": "2.20",
    "ease": -0.263,
    "marketLine": "9.5",
    "betRating": "💪 STRONG PLAY",
    "confidence": 0.8141176470588236,
    "confidenceGrade": "B+",
    "score": "7.16",
    "interpretation": "Matchup: Negative Ease → Environment suppresses stat (Confirms Under). | Pos: <span style=\"color:#f87171\">-0.26</span> | Team: <span style=\"color:#4ade80\">0.19</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.20 point gap** vs public perception.<br>🔒 **Defensive Clamp**: CHI ranks elite vs Assists. Expect usage to struggle.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T01:10:00Z"
  },
  {
    "player": "Jamal Murray",
    "team": "DEN",
    "pos": "PG",
    "opp": "LAL",
    "stat": "pr",
    "side": "UNDER",
    "line": 32.5,
    "projection": "29.03",
    "edge": "3.47",
    "ease": 0.132,
    "marketLine": "32.5",
    "betRating": "💪 STRONG PLAY",
    "confidence": 0.8974117647058827,
    "confidenceGrade": "A",
    "score": "7.01",
    "interpretation": "Matchup: Positive Ease → Contradicts Under. | Pos: <span style=\"color:#4ade80\">0.13</span> | Team: <span style=\"color:#f87171\">-0.58</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.47 point gap** vs public perception.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Domantas Sabonis",
    "team": "SAC",
    "pos": "C",
    "opp": "MIA",
    "stat": "r",
    "side": "OVER",
    "line": 8.5,
    "projection": "10.56",
    "edge": "2.06",
    "ease": 1.189,
    "marketLine": "8.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.893529411764706,
    "confidenceGrade": "A",
    "score": "6.90",
    "interpretation": "Matchup: Positive Ease → Environment supports stat accumulation. | Pos: <span style=\"color:#4ade80\">1.19</span> | Team: <span style=\"color:#4ade80\">1.45</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.06 point gap** vs public perception.<br>✅ **Smash Spot**: MIA defense is bleeding Rebounds to this position (Ease: +1.189). High ceiling environment.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "VJ Edgecombe",
    "team": "PHI",
    "pos": "PG",
    "opp": "PHO",
    "stat": "pra",
    "side": "OVER",
    "line": 24.5,
    "projection": "28.32",
    "edge": "3.82",
    "ease": -0.4333333333333334,
    "marketLine": "24.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.8320000000000001,
    "confidenceGrade": "A-",
    "score": "6.75",
    "interpretation": "Matchup: Negative Ease → Contradicts Over (check usage). | Pos: <span style=\"color:#f87171\">-0.43</span> | Team: <span style=\"color:#f87171\">-0.12</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.82 point gap** vs public perception.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T00:10:00Z"
  },
  {
    "player": "James Harden",
    "team": "LAC",
    "pos": "PG",
    "opp": "CHI",
    "stat": "pra",
    "side": "UNDER",
    "line": 45,
    "projection": "41.03",
    "edge": "3.97",
    "ease": -0.21800000000000005,
    "marketLine": "45",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.7969999999999998,
    "confidenceGrade": "B+",
    "score": "6.72",
    "interpretation": "Matchup: Negative Ease → Environment suppresses stat (Confirms Under). | Pos: <span style=\"color:#f87171\">-0.22</span> | Team: <span style=\"color:#4ade80\">0.42</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.97 point gap** vs public perception.<br>🔒 **Defensive Clamp**: CHI ranks elite vs Pts+Reb+Ast. Expect usage to struggle.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T01:10:00Z"
  },
  {
    "player": "Anthony Edwards",
    "team": "MIN",
    "pos": "PG",
    "opp": "UTA",
    "stat": "pr",
    "side": "UNDER",
    "line": 35.5,
    "projection": "32.13",
    "edge": "3.37",
    "ease": -0.238,
    "marketLine": "35.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.8868235294117645,
    "confidenceGrade": "A",
    "score": "6.72",
    "interpretation": "Matchup: Negative Ease → Environment suppresses stat (Confirms Under). | Pos: <span style=\"color:#f87171\">-0.24</span> | Team: <span style=\"color:#4ade80\">0.79</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.37 point gap** vs public perception.<br>🔒 **Defensive Clamp**: UTA ranks elite vs Pts+Reb. Expect usage to struggle.",
    "startTime": "2026-01-21T02:10:00Z"
  },
  {
    "player": "Paul George",
    "team": "PHI",
    "pos": "SG",
    "opp": "PHO",
    "stat": "pr",
    "side": "OVER",
    "line": 21.5,
    "projection": "25.06",
    "edge": "3.56",
    "ease": 0.4575,
    "marketLine": "21.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.8269411764705885,
    "confidenceGrade": "A-",
    "score": "6.62",
    "interpretation": "Matchup: Positive Ease → Environment supports stat accumulation. | Pos: <span style=\"color:#4ade80\">0.46</span> | Team: <span style=\"color:#4ade80\">0.11</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.56 point gap** vs public perception.<br>✅ **Smash Spot**: PHO defense is bleeding Pts+Reb to this position (Ease: +0.4575). High ceiling environment.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T00:10:00Z"
  },
  {
    "player": "Ace Bailey",
    "team": "UTA",
    "pos": "SG",
    "opp": "MIN",
    "stat": "pra",
    "side": "UNDER",
    "line": 19.5,
    "projection": "15.76",
    "edge": "3.74",
    "ease": -0.17733333333333326,
    "marketLine": "19.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.8240000000000001,
    "confidenceGrade": "A-",
    "score": "6.55",
    "interpretation": "Matchup: Negative Ease → Environment suppresses stat (Confirms Under). | Pos: <span style=\"color:#f87171\">-0.18</span> | Team: <span style=\"color:#f87171\">-0.35</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.74 point gap** vs public perception.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T02:10:00Z"
  },
  {
    "player": "Scottie Barnes",
    "team": "TOR",
    "pos": "SG",
    "opp": "GSW",
    "stat": "pr",
    "side": "UNDER",
    "line": 29.5,
    "projection": "26.27",
    "edge": "3.23",
    "ease": -0.49799999999999994,
    "marketLine": "29.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.8720000000000001,
    "confidenceGrade": "A-",
    "score": "6.34",
    "interpretation": "Matchup: Negative Ease → Environment suppresses stat (Confirms Under). | Pos: <span style=\"color:#f87171\">-0.50</span> | Team: <span style=\"color:#f87171\">-0.19</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.23 point gap** vs public perception.<br>🔒 **Defensive Clamp**: GSW ranks elite vs Pts+Reb. Expect usage to struggle.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Scottie Barnes",
    "team": "TOR",
    "pos": "SG",
    "opp": "GSW",
    "stat": "p",
    "side": "UNDER",
    "line": 20.5,
    "projection": "17.75",
    "edge": "2.75",
    "ease": -0.10800000000000003,
    "marketLine": "20.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.8535294117647059,
    "confidenceGrade": "A-",
    "score": "5.87",
    "interpretation": "Matchup: Negative Ease → Environment suppresses stat (Confirms Under). | Pos: <span style=\"color:#f87171\">-0.11</span> | Team: <span style=\"color:#f87171\">-0.72</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.75 point gap** vs public perception.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "VJ Edgecombe",
    "team": "PHI",
    "pos": "PG",
    "opp": "PHO",
    "stat": "pa",
    "side": "OVER",
    "line": 19.5,
    "projection": "22.76",
    "edge": "3.26",
    "ease": -0.2695,
    "marketLine": "19.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.795176470588235,
    "confidenceGrade": "B+",
    "score": "5.83",
    "interpretation": "Matchup: Negative Ease → Contradicts Over (check usage). | Pos: <span style=\"color:#f87171\">-0.27</span> | Team: <span style=\"color:#f87171\">-0.40</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.26 point gap** vs public perception.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T00:10:00Z"
  },
  {
    "player": "Scottie Barnes",
    "team": "TOR",
    "pos": "SG",
    "opp": "GSW",
    "stat": "pra",
    "side": "UNDER",
    "line": 34.5,
    "projection": "31.30",
    "edge": "3.20",
    "ease": -0.20066666666666663,
    "marketLine": "34.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.8499999999999999,
    "confidenceGrade": "A-",
    "score": "5.78",
    "interpretation": "Matchup: Negative Ease → Environment suppresses stat (Confirms Under). | Pos: <span style=\"color:#f87171\">-0.20</span> | Team: <span style=\"color:#f87171\">-0.08</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.20 point gap** vs public perception.<br>🔒 **Defensive Clamp**: GSW ranks elite vs Pts+Reb+Ast. Expect usage to struggle.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Draymond Green",
    "team": "GSW",
    "pos": "PF",
    "opp": "TOR",
    "stat": "pa",
    "side": "UNDER",
    "line": 16.5,
    "projection": "13.32",
    "edge": "3.18",
    "ease": -0.30600000000000005,
    "marketLine": "16.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.7867058823529413,
    "confidenceGrade": "B+",
    "score": "5.63",
    "interpretation": "Matchup: Negative Ease → Environment suppresses stat (Confirms Under). | Pos: <span style=\"color:#f87171\">-0.31</span> | Team: <span style=\"color:#f87171\">-0.51</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.18 point gap** vs public perception.<br>🔒 **Defensive Clamp**: TOR ranks elite vs Pts+Ast. Expect usage to struggle.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Josh Giddey",
    "team": "CHI",
    "pos": "PG",
    "opp": "LAC",
    "stat": "ra",
    "side": "OVER",
    "line": 14,
    "projection": "16.40",
    "edge": "2.40",
    "ease": 0.273,
    "marketLine": "14",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.8405882352941175,
    "confidenceGrade": "A-",
    "score": "5.55",
    "interpretation": "Matchup: Positive Ease → Environment supports stat accumulation. | Pos: <span style=\"color:#4ade80\">0.27</span> | Team: <span style=\"color:#f87171\">-0.32</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.40 point gap** vs public perception.<br>✅ **Smash Spot**: LAC defense is bleeding Reb+Ast to this position (Ease: +0.273). High ceiling environment.",
    "startTime": "2026-01-21T01:10:00Z"
  },
  {
    "player": "James Harden",
    "team": "LAC",
    "pos": "PG",
    "opp": "CHI",
    "stat": "pa",
    "side": "UNDER",
    "line": 39.5,
    "projection": "36.22",
    "edge": "3.28",
    "ease": -0.15100000000000002,
    "marketLine": "39.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.747294117647059,
    "confidenceGrade": "B",
    "score": "5.52",
    "interpretation": "Matchup: Negative Ease → Environment suppresses stat (Confirms Under). | Pos: <span style=\"color:#f87171\">-0.15</span> | Team: <span style=\"color:#4ade80\">0.63</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.28 point gap** vs public perception.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T01:10:00Z"
  },
  {
    "player": "Immanuel Quickley",
    "team": "TOR",
    "pos": "PG",
    "opp": "GSW",
    "stat": "p",
    "side": "OVER",
    "line": 16.5,
    "projection": "19.12",
    "edge": "2.62",
    "ease": -0.201,
    "marketLine": "16.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.8382352941176472,
    "confidenceGrade": "A-",
    "score": "5.49",
    "interpretation": "Matchup: Negative Ease → Contradicts Over (check usage). | Pos: <span style=\"color:#f87171\">-0.20</span> | Team: <span style=\"color:#f87171\">-0.72</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.62 point gap** vs public perception.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Tre Jones",
    "team": "CHI",
    "pos": "PG",
    "opp": "LAC",
    "stat": "pa",
    "side": "OVER",
    "line": 12.5,
    "projection": "15.40",
    "edge": "2.90",
    "ease": -0.2225,
    "marketLine": "12.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.8370588235294116,
    "confidenceGrade": "A-",
    "score": "5.46",
    "interpretation": "Matchup: Negative Ease → Contradicts Over (check usage). | Pos: <span style=\"color:#f87171\">-0.22</span> | Team: <span style=\"color:#f87171\">-0.39</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.90 point gap** vs public perception.",
    "startTime": "2026-01-21T01:10:00Z"
  },
  {
    "player": "Domantas Sabonis",
    "team": "SAC",
    "pos": "C",
    "opp": "MIA",
    "stat": "pr",
    "side": "OVER",
    "line": 22.5,
    "projection": "25.39",
    "edge": "2.89",
    "ease": 0.746,
    "marketLine": "22.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.8360000000000001,
    "confidenceGrade": "A-",
    "score": "5.44",
    "interpretation": "Matchup: Positive Ease → Environment supports stat accumulation. | Pos: <span style=\"color:#4ade80\">0.75</span> | Team: <span style=\"color:#4ade80\">0.97</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.89 point gap** vs public perception.<br>✅ **Smash Spot**: MIA defense is bleeding Pts+Reb to this position (Ease: +0.746). High ceiling environment.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Anthony Edwards",
    "team": "MIN",
    "pos": "PG",
    "opp": "UTA",
    "stat": "p",
    "side": "UNDER",
    "line": 30,
    "projection": "27.41",
    "edge": "2.59",
    "ease": 0.30099999999999993,
    "marketLine": "30",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.8347058823529412,
    "confidenceGrade": "A-",
    "score": "5.40",
    "interpretation": "Matchup: Positive Ease → Contradicts Under. | Pos: <span style=\"color:#4ade80\">0.30</span> | Team: <span style=\"color:#4ade80\">1.53</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.59 point gap** vs public perception.<br>✅ **Smash Spot**: UTA defense is bleeding Points to this position (Ease: +0.30099999999999993). High ceiling environment.",
    "startTime": "2026-01-21T02:10:00Z"
  },
  {
    "player": "Nikola Vucevic",
    "team": "CHI",
    "pos": "C",
    "opp": "LAC",
    "stat": "pr",
    "side": "UNDER",
    "line": 25.5,
    "projection": "22.71",
    "edge": "2.79",
    "ease": 0.16250000000000003,
    "marketLine": "25.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.8254117647058823,
    "confidenceGrade": "A-",
    "score": "5.18",
    "interpretation": "Matchup: Positive Ease → Contradicts Under. | Pos: <span style=\"color:#4ade80\">0.16</span> | Team: <span style=\"color:#f87171\">-0.72</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.79 point gap** vs public perception.",
    "startTime": "2026-01-21T01:10:00Z"
  },
  {
    "player": "Paul George",
    "team": "PHI",
    "pos": "SG",
    "opp": "PHO",
    "stat": "pra",
    "side": "OVER",
    "line": 25.5,
    "projection": "28.67",
    "edge": "3.17",
    "ease": -0.025666666666666654,
    "marketLine": "25.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.7670000000000002,
    "confidenceGrade": "B+",
    "score": "5.17",
    "interpretation": "Matchup: Neutral Ease → Edge drives the bet. | Pos: <span style=\"color:#f87171\">-0.03</span> | Team: <span style=\"color:#f87171\">-0.12</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.17 point gap** vs public perception.<br>⚖️ **Neutral Spot**: Matchup is average, but the volume projection (28.7) carries the play.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T00:10:00Z"
  },
  {
    "player": "John Collins",
    "team": "LAC",
    "pos": "PF",
    "opp": "CHI",
    "stat": "pr",
    "side": "OVER",
    "line": 19.5,
    "projection": "22.59",
    "edge": "3.09",
    "ease": 1.088,
    "marketLine": "19.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.7371764705882352,
    "confidenceGrade": "B",
    "score": "5.13",
    "interpretation": "Matchup: Positive Ease → Environment supports stat accumulation. | Pos: <span style=\"color:#4ade80\">1.09</span> | Team: <span style=\"color:#4ade80\">0.54</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.09 point gap** vs public perception.<br>✅ **Smash Spot**: CHI defense is bleeding Pts+Reb to this position (Ease: +1.088). High ceiling environment.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T01:10:00Z"
  },
  {
    "player": "Josh Giddey",
    "team": "CHI",
    "pos": "PG",
    "opp": "LAC",
    "stat": "r",
    "side": "OVER",
    "line": 6.5,
    "projection": "8.14",
    "edge": "1.64",
    "ease": 0.5900000000000001,
    "marketLine": "6.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.8194117647058825,
    "confidenceGrade": "B+",
    "score": "5.04",
    "interpretation": "Matchup: Positive Ease → Environment supports stat accumulation. | Pos: <span style=\"color:#4ade80\">0.59</span> | Team: <span style=\"color:#f87171\">-0.66</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **1.64 point gap** vs public perception.<br>✅ **Smash Spot**: LAC defense is bleeding Rebounds to this position (Ease: +0.5900000000000001). High ceiling environment.",
    "startTime": "2026-01-21T01:10:00Z"
  },
  {
    "player": "Nikola Vucevic",
    "team": "CHI",
    "pos": "C",
    "opp": "LAC",
    "stat": "pra",
    "side": "UNDER",
    "line": 29,
    "projection": "26.14",
    "edge": "2.86",
    "ease": 0.26300000000000007,
    "marketLine": "29",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.8160000000000001,
    "confidenceGrade": "B+",
    "score": "4.96",
    "interpretation": "Matchup: Positive Ease → Contradicts Under. | Pos: <span style=\"color:#4ade80\">0.26</span> | Team: <span style=\"color:#f87171\">-0.48</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.86 point gap** vs public perception.<br>✅ **Smash Spot**: LAC defense is bleeding Pts+Reb+Ast to this position (Ease: +0.26300000000000007). High ceiling environment.",
    "startTime": "2026-01-21T01:10:00Z"
  },
  {
    "player": "Stephon Castle",
    "team": "SAS",
    "pos": "PG",
    "opp": "HOU",
    "stat": "pa",
    "side": "UNDER",
    "line": 22.5,
    "projection": "19.60",
    "edge": "2.90",
    "ease": 0.6555,
    "marketLine": "22.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.7570588235294116,
    "confidenceGrade": "B",
    "score": "4.94",
    "interpretation": "Matchup: Positive Ease → Contradicts Under. | Pos: <span style=\"color:#4ade80\">0.66</span> | Team: <span style=\"color:#f87171\">-0.66</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.90 point gap** vs public perception.<br>✅ **Smash Spot**: HOU defense is bleeding Pts+Ast to this position (Ease: +0.6555). High ceiling environment.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T01:10:00Z"
  },
  {
    "player": "Immanuel Quickley",
    "team": "TOR",
    "pos": "PG",
    "opp": "GSW",
    "stat": "pra",
    "side": "OVER",
    "line": 26.5,
    "projection": "29.34",
    "edge": "2.84",
    "ease": -0.1566666666666667,
    "marketLine": "26.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.8140000000000001,
    "confidenceGrade": "B+",
    "score": "4.91",
    "interpretation": "Matchup: Negative Ease → Contradicts Over (check usage). | Pos: <span style=\"color:#f87171\">-0.16</span> | Team: <span style=\"color:#f87171\">-0.08</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.84 point gap** vs public perception.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Paul George",
    "team": "PHI",
    "pos": "SG",
    "opp": "PHO",
    "stat": "p",
    "side": "OVER",
    "line": 16.5,
    "projection": "19.09",
    "edge": "2.59",
    "ease": 0.53,
    "marketLine": "16.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.7547058823529412,
    "confidenceGrade": "B",
    "score": "4.89",
    "interpretation": "Matchup: Positive Ease → Environment supports stat accumulation. | Pos: <span style=\"color:#4ade80\">0.53</span> | Team: <span style=\"color:#f87171\">-0.20</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.59 point gap** vs public perception.<br>✅ **Smash Spot**: PHO defense is bleeding Points to this position (Ease: +0.53). High ceiling environment.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T00:10:00Z"
  },
  {
    "player": "Nikola Vucevic",
    "team": "CHI",
    "pos": "C",
    "opp": "LAC",
    "stat": "p",
    "side": "UNDER",
    "line": 17,
    "projection": "14.62",
    "edge": "2.38",
    "ease": 0.633,
    "marketLine": "17",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.8099999999999998,
    "confidenceGrade": "B+",
    "score": "4.82",
    "interpretation": "Matchup: Positive Ease → Contradicts Under. | Pos: <span style=\"color:#4ade80\">0.63</span> | Team: <span style=\"color:#f87171\">-0.79</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.38 point gap** vs public perception.<br>✅ **Smash Spot**: LAC defense is bleeding Points to this position (Ease: +0.633). High ceiling environment.",
    "startTime": "2026-01-21T01:10:00Z"
  },
  {
    "player": "Jamal Murray",
    "team": "DEN",
    "pos": "PG",
    "opp": "LAL",
    "stat": "p",
    "side": "UNDER",
    "line": 27.5,
    "projection": "25.15",
    "edge": "2.35",
    "ease": 1.185,
    "marketLine": "27.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.8064705882352943,
    "confidenceGrade": "B+",
    "score": "4.74",
    "interpretation": "Matchup: Positive Ease → Contradicts Under. | Pos: <span style=\"color:#4ade80\">1.19</span> | Team: <span style=\"color:#4ade80\">0.40</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.35 point gap** vs public perception.<br>✅ **Smash Spot**: LAL defense is bleeding Points to this position (Ease: +1.185). High ceiling environment.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Anthony Edwards",
    "team": "MIN",
    "pos": "PG",
    "opp": "UTA",
    "stat": "pa",
    "side": "UNDER",
    "line": 34,
    "projection": "31.45",
    "edge": "2.55",
    "ease": 0.30399999999999994,
    "marketLine": "34",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.8,
    "confidenceGrade": "B+",
    "score": "4.59",
    "interpretation": "Matchup: Positive Ease → Contradicts Under. | Pos: <span style=\"color:#4ade80\">0.30</span> | Team: <span style=\"color:#4ade80\">1.48</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.55 point gap** vs public perception.<br>✅ **Smash Spot**: UTA defense is bleeding Pts+Ast to this position (Ease: +0.30399999999999994). High ceiling environment.",
    "startTime": "2026-01-21T02:10:00Z"
  },
  {
    "player": "Immanuel Quickley",
    "team": "TOR",
    "pos": "PG",
    "opp": "GSW",
    "stat": "pa",
    "side": "OVER",
    "line": 22.5,
    "projection": "25.05",
    "edge": "2.55",
    "ease": -0.3325,
    "marketLine": "22.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.8,
    "confidenceGrade": "B+",
    "score": "4.59",
    "interpretation": "Matchup: Negative Ease → Contradicts Over (check usage). | Pos: <span style=\"color:#f87171\">-0.33</span> | Team: <span style=\"color:#f87171\">-0.28</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.55 point gap** vs public perception.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Paul George",
    "team": "PHI",
    "pos": "SG",
    "opp": "PHO",
    "stat": "pa",
    "side": "OVER",
    "line": 20,
    "projection": "22.70",
    "edge": "2.70",
    "ease": -0.23099999999999998,
    "marketLine": "20",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.7358823529411764,
    "confidenceGrade": "B",
    "score": "4.47",
    "interpretation": "Matchup: Negative Ease → Contradicts Over (check usage). | Pos: <span style=\"color:#f87171\">-0.23</span> | Team: <span style=\"color:#f87171\">-0.40</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.70 point gap** vs public perception.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T00:10:00Z"
  },
  {
    "player": "Stephen Curry",
    "team": "GSW",
    "pos": "PG",
    "opp": "TOR",
    "stat": "ra",
    "side": "UNDER",
    "line": 10.5,
    "projection": "8.20",
    "edge": "2.30",
    "ease": -0.23500000000000004,
    "marketLine": "10.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.6976470588235296,
    "confidenceGrade": "C",
    "score": "4.41",
    "interpretation": "Matchup: Negative Ease → Environment suppresses stat (Confirms Under). | Pos: <span style=\"color:#f87171\">-0.24</span> | Team: <span style=\"color:#f87171\">-0.97</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.30 point gap** vs public perception.<br>🔒 **Defensive Clamp**: TOR ranks elite vs Reb+Ast. Expect usage to struggle.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "John Collins",
    "team": "LAC",
    "pos": "PF",
    "opp": "CHI",
    "stat": "p",
    "side": "OVER",
    "line": 14,
    "projection": "16.45",
    "edge": "2.45",
    "ease": 2.172,
    "marketLine": "14",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.6982352941176468,
    "confidenceGrade": "C",
    "score": "4.28",
    "interpretation": "Matchup: Positive Ease → Environment supports stat accumulation. | Pos: <span style=\"color:#4ade80\">2.17</span> | Team: <span style=\"color:#4ade80\">1.06</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.45 point gap** vs public perception.<br>✅ **Smash Spot**: CHI defense is bleeding Points to this position (Ease: +2.172). High ceiling environment.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T01:10:00Z"
  },
  {
    "player": "Donte DiVincenzo",
    "team": "MIN",
    "pos": "PG",
    "opp": "UTA",
    "stat": "a",
    "side": "UNDER",
    "line": 5.5,
    "projection": "4.14",
    "edge": "1.36",
    "ease": 0.307,
    "marketLine": "5.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.786,
    "confidenceGrade": "B+",
    "score": "4.28",
    "interpretation": "Matchup: Positive Ease → Contradicts Under. | Pos: <span style=\"color:#4ade80\">0.31</span> | Team: <span style=\"color:#4ade80\">1.43</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **1.36 point gap** vs public perception.<br>✅ **Smash Spot**: UTA defense is bleeding Assists to this position (Ease: +0.307). High ceiling environment.",
    "startTime": "2026-01-21T02:10:00Z"
  },
  {
    "player": "Keyonte George",
    "team": "UTA",
    "pos": "PG",
    "opp": "MIN",
    "stat": "ra",
    "side": "OVER",
    "line": 9.5,
    "projection": "11.63",
    "edge": "2.13",
    "ease": 0.14750000000000002,
    "marketLine": "9.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.7256470588235293,
    "confidenceGrade": "B",
    "score": "4.25",
    "interpretation": "Matchup: Positive Ease → Environment supports stat accumulation. | Pos: <span style=\"color:#4ade80\">0.15</span> | Team: <span style=\"color:#f87171\">-0.59</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.13 point gap** vs public perception.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T02:10:00Z"
  },
  {
    "player": "Stephen Curry",
    "team": "GSW",
    "pos": "PG",
    "opp": "TOR",
    "stat": "p",
    "side": "OVER",
    "line": 28.5,
    "projection": "30.96",
    "edge": "2.46",
    "ease": 0.402,
    "marketLine": "28.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.6894117647058821,
    "confidenceGrade": "C",
    "score": "4.24",
    "interpretation": "Matchup: Positive Ease → Environment supports stat accumulation. | Pos: <span style=\"color:#4ade80\">0.40</span> | Team: <span style=\"color:#4ade80\">0.02</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.46 point gap** vs public perception.<br>✅ **Smash Spot**: TOR defense is bleeding Points to this position (Ease: +0.402). High ceiling environment.<br>⚠️ **Back-to-Back**: Player is on 0 days rest. Fatigue penalty applied.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Coby White",
    "team": "CHI",
    "pos": "PG",
    "opp": "LAC",
    "stat": "pra",
    "side": "OVER",
    "line": 25.5,
    "projection": "28.13",
    "edge": "2.63",
    "ease": 0.04833333333333336,
    "marketLine": "25.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.7529999999999999,
    "confidenceGrade": "B",
    "score": "4.21",
    "interpretation": "Matchup: Neutral Ease → Edge drives the bet. | Pos: <span style=\"color:#4ade80\">0.05</span> | Team: <span style=\"color:#f87171\">-0.48</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **2.63 point gap** vs public perception.<br>⚖️ **Neutral Spot**: Matchup is average, but the volume projection (28.1) carries the play.",
    "startTime": "2026-01-21T01:10:00Z"
  },
  {
    "player": "Scottie Barnes",
    "team": "TOR",
    "pos": "SG",
    "opp": "GSW",
    "stat": "b",
    "side": "OVER",
    "line": 0.5,
    "projection": "1.11",
    "edge": "0.61",
    "ease": 0.509,
    "marketLine": "0.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.7811764705882354,
    "confidenceGrade": "B+",
    "score": "4.17",
    "interpretation": "Matchup: Positive Ease → Environment supports stat accumulation. | Pos: <span style=\"color:#4ade80\">0.51</span> | Team: <span style=\"color:#4ade80\">0.15</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **0.61 point gap** vs public perception.<br>✅ **Smash Spot**: GSW defense is bleeding Blocks to this position (Ease: +0.509). High ceiling environment.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Immanuel Quickley",
    "team": "TOR",
    "pos": "PG",
    "opp": "GSW",
    "stat": "s",
    "side": "OVER",
    "line": 0.5,
    "projection": "1.10",
    "edge": "0.60",
    "ease": -0.406,
    "marketLine": "0.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.7770588235294118,
    "confidenceGrade": "B+",
    "score": "4.08",
    "interpretation": "Matchup: Negative Ease → Contradicts Over (check usage). | Pos: <span style=\"color:#f87171\">-0.41</span> | Team: <span style=\"color:#f87171\">-0.54</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **0.60 point gap** vs public perception.",
    "startTime": "2026-01-21T03:10:00Z"
  },
  {
    "player": "Alperen Sengun",
    "team": "HOU",
    "pos": "PF",
    "opp": "SAS",
    "stat": "ra",
    "side": "OVER",
    "line": 14.5,
    "projection": "16.39",
    "edge": "1.89",
    "ease": -0.27649999999999997,
    "marketLine": "14.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.7745882352941178,
    "confidenceGrade": "B+",
    "score": "4.03",
    "interpretation": "Matchup: Negative Ease → Contradicts Over (check usage). | Pos: <span style=\"color:#f87171\">-0.28</span> | Team: <span style=\"color:#f87171\">-0.11</span>",
    "analysis": "🎯 **Solid Edge**: Model identifies a **1.89 point gap** vs public perception.",
    "startTime": "2026-01-21T01:10:00Z"
  }
];