window.LAST_UPDATED = "1/27/2026, 4:46:31 PM";
window.PROPHET_RECORD = {
  "season": {
    "w": 231,
    "l": 206,
    "p": 0,
    "total": 437,
    "pct": 53
  },
  "locks": {
    "w": 29,
    "l": 9,
    "p": 0,
    "total": 38,
    "pct": 76
  },
  "diamond": {
    "w": 10,
    "l": 9,
    "p": 0,
    "total": 19,
    "pct": 53
  },
  "elite": {
    "w": 12,
    "l": 14,
    "p": 0,
    "total": 26,
    "pct": 46
  }
};
window.LATEST_PICKS = [
  {
    "player": "Joel Embiid",
    "team": "PHI",
    "pos": "C",
    "opp": "MIL",
    "stat": "pr",
    "side": "UNDER",
    "line": 36.5,
    "projection": "32.10",
    "edge": "4.40",
    "ease": 0,
    "posEase": 0,
    "teamEase": 0,
    "usg": 29.571922915221837,
    "marketLine": "36.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.42,
    "confidenceGrade": "C",
    "score": "3.96",
    "interpretation": "Neutral Ease → Edge drives the bet.",
    "analysis": "🎯 **Solid Edge**: Model identifies a **4.40 point gap** vs public perception.<br>⚠️ **Last 5 Games**: Shaky Form (1/5 Hits). Avg: 39.4. <span style='color:#f87171'>(-10% Penalty)</span>",
    "startTime": "2026-01-28T01:10:00Z"
  },
  {
    "player": "Joel Embiid",
    "team": "PHI",
    "pos": "C",
    "opp": "MIL",
    "stat": "pra",
    "side": "UNDER",
    "line": 40.5,
    "projection": "36.17",
    "edge": "4.33",
    "ease": 0,
    "posEase": 0,
    "teamEase": 0,
    "usg": 29.571922915221837,
    "marketLine": "40.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.42,
    "confidenceGrade": "C",
    "score": "3.90",
    "interpretation": "Neutral Ease → Edge drives the bet.",
    "analysis": "🎯 **Solid Edge**: Model identifies a **4.33 point gap** vs public perception.<br>⚠️ **Last 5 Games**: Shaky Form (1/5 Hits). Avg: 44.4. <span style='color:#f87171'>(-10% Penalty)</span>",
    "startTime": "2026-01-28T01:10:00Z"
  },
  {
    "player": "Kyle Filipowski",
    "team": "UTA",
    "pos": "PF",
    "opp": "LAC",
    "stat": "pra",
    "side": "OVER",
    "line": 20,
    "projection": "24.00",
    "edge": "4.00",
    "ease": 0,
    "posEase": 0,
    "teamEase": 0,
    "usg": 19.341657475624277,
    "marketLine": "19.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.42,
    "confidenceGrade": "C",
    "score": "3.60",
    "interpretation": "Neutral Ease → Edge drives the bet.",
    "analysis": "🎯 **Solid Edge**: Model identifies a **4.00 point gap** vs public perception.<br>➡️ **Last 5 Games**: Steady (3/5 Hits). Avg: 20.0. <span style='color:#cbd5e1'>(No Adjustment)</span>",
    "startTime": "2026-01-28T03:10:00Z"
  },
  {
    "player": "Paul George",
    "team": "PHI",
    "pos": "SG",
    "opp": "MIL",
    "stat": "pr",
    "side": "OVER",
    "line": 19.5,
    "projection": "23.29",
    "edge": "3.79",
    "ease": 0,
    "posEase": 0,
    "teamEase": 0,
    "usg": 21.80738866869572,
    "marketLine": "19.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.42,
    "confidenceGrade": "C",
    "score": "3.41",
    "interpretation": "Neutral Ease → Edge drives the bet.",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.79 point gap** vs public perception.<br>⚠️ **Last 5 Games**: Shaky Form (1/5 Hits). Avg: 17.8. <span style='color:#f87171'>(-10% Penalty)</span>",
    "startTime": "2026-01-28T01:10:00Z"
  },
  {
    "player": "Paul George",
    "team": "PHI",
    "pos": "SG",
    "opp": "MIL",
    "stat": "pra",
    "side": "OVER",
    "line": 23.5,
    "projection": "27.26",
    "edge": "3.76",
    "ease": 0,
    "posEase": 0,
    "teamEase": 0,
    "usg": 21.80738866869572,
    "marketLine": "23.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.42,
    "confidenceGrade": "C",
    "score": "3.38",
    "interpretation": "Neutral Ease → Edge drives the bet.",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.76 point gap** vs public perception.<br>➡️ **Last 5 Games**: Steady (2/5 Hits). Avg: 22.0. <span style='color:#cbd5e1'>(No Adjustment)</span>",
    "startTime": "2026-01-28T01:10:00Z"
  },
  {
    "player": "Kyle Filipowski",
    "team": "UTA",
    "pos": "PF",
    "opp": "LAC",
    "stat": "pr",
    "side": "OVER",
    "line": 18,
    "projection": "21.37",
    "edge": "3.37",
    "ease": 0,
    "posEase": 0,
    "teamEase": 0,
    "usg": 19.341657475624277,
    "marketLine": "17.5",
    "betRating": "✅ SOLID PLAY",
    "confidence": 0.42,
    "confidenceGrade": "C",
    "score": "3.03",
    "interpretation": "Neutral Ease → Edge drives the bet.",
    "analysis": "🎯 **Solid Edge**: Model identifies a **3.37 point gap** vs public perception.<br>➡️ **Last 5 Games**: Steady (3/5 Hits). Avg: 17.2. <span style='color:#cbd5e1'>(No Adjustment)</span>",
    "startTime": "2026-01-28T03:10:00Z"
  }
];